### ISSUE TITLE
Agrandir légèrement toutes les illustrations dans le parcours.

### ISSUE THREAD

**Issue by nicolaskempf57** [datagouv/front-end#201]

**Comment by nicolaskempf57** [comment]
@agarrone Je veux bien plus de détails sur ce point lors de ta 2e passe sur l'admin parce que j'ai l'impression que les images ont les mêmes tailles que sur Figma

**Comment by agarrone** [comment]
Maquette 
![image](https://github.com/user-attachments/assets/44d2eea0-6f9c-4fc1-a7be-db39d34b9934)



VS ce que je vois 
<img width="766" alt="image" src="https://github.com/user-attachments/assets/b1c796c4-b727-4026-846b-00a58d9193a5" />
